config/routes.rb
Rankable::Application.routes.draw do

  resources :awards, :except => [:show]
  resources :matches, :except => [:new] do
    resources :awards, :except => [:show]
  end

  resources :tournaments do
    resources :matches
  end

  resources :users, :only => [:index, :show], :path => "organisers"

  devise_for :users

  root :to => 'home#index'

end

app/models/tournament.rb
class Tournament < ActiveRecord::Base
  belongs_to :user
  attr_accessible :name, :start

  has_many :matches

  validates_presence_of :name, :user

  validates_associated :user

  def participants
    usernames = []

    Award.joins(:match).where(:matches => { 
                              :tournament_id => id }
             ).select(:username).uniq.each do |award|
               usernames.push award.username
             end

    usernames
  end

  # Get a list of participants and their scores
  #
  # Returns an containing [name, num_wins]
  def results

    result_list = {}

    matches.each do |match|
      if match.winner
        match.winner.each do |winner|
          name = winner

          count = 1
          count = result_list[name] + 1 if result_list[name]

          result_list.merge!({ winner => count})    
        end
      end
    end

    result_list.to_a.sort { |a, b| -( a[1] <=> b[1] ) }
  end
end

app/controllers/tournaments_controller.rb
class TournamentsController < ApplicationController
  load_and_authorize_resource

  # GET /tournaments
  # GET /tournaments.json
  def index
    if params[:user_id]
      @tournaments = Tournament.where(:user_id => params[:user_id])
    else
      @tournaments = Tournament.order('start').all
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tournaments }
    end
  end

  # GET /tournaments/1
  # GET /tournaments/1.json
  def show
    @tournament = Tournament.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @tournament }
    end
  end

  # GET /tournaments/new
  # GET /tournaments/new.json
  def new
    @tournament = Tournament.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @tournament }
    end
  end

  # GET /tournaments/1/edit
  def edit
    @tournament = Tournament.find(params[:id])
  end

  # POST /tournaments
  # POST /tournaments.json
  def create
    @tournament = Tournament.new(params[:tournament])
    
    @user = params[:tournament][:user]
    @user = current_user unless @user

    @tournament.user = @user

    respond_to do |format|
      if @tournament.save
        format.html { redirect_to @tournament, notice: 'Tournament was successfully created.' }
        format.json { render json: @tournament, status: :created, location: @tournament }
      else
        format.html { render action: "new" }
        format.json { render json: @tournament.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tournaments/1
  # PUT /tournaments/1.json
  def update
    @tournament = Tournament.find(params[:id])

    respond_to do |format|
      if @tournament.update_attributes(params[:tournament])
        format.html { redirect_to @tournament, notice: 'Tournament was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @tournament.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tournaments/1
  # DELETE /tournaments/1.json
  def destroy
    @tournament = Tournament.find(params[:id])
    @tournament.destroy

    respond_to do |format|
      format.html { redirect_to tournaments_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/tournaments_helper.rb
module TournamentsHelper
end

app/views/tournaments/_form.html.haml
= form_for @tournament do |f|
  - if @tournament.errors.any?
    #error_explanation
      %h2= "#{pluralize(@tournament.errors.count, "error")} prohibited this tournament from being saved:"
      %ul
        - @tournament.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name

  -# TODO: May be useful for admin
  -#.field
    -#= f.label :user
    -#= f.text_field :user

  .field
    = f.label :start
    = f.date_select :start, :start_year => Date.today.year - 1
  .actions
    = f.submit 'Save'

app/views/tournaments/edit.html.haml
%h1 Editing tournament

= render 'form'

= link_to 'Show', @tournament
\|
= link_to 'Back', tournaments_path

app/views/tournaments/index.html.haml
%h1 
  = "Personal" if @user_page
  Tournaments

%table{:class => %w(table table-bordered table-striped)}
  %tr
    %th Name
    %th Start
    %th
    %th
    %th

  - @tournaments.each do |tournament|
    %tr
      %td= tournament.name
      %td= tournament.start
      %td= link_to 'Show', tournament
      %td= link_to 'Edit', edit_tournament_path(tournament)
      %td= link_to 'Destroy', tournament, :method => :delete, :data => { :confirm => 'Are you sure?' }

- if current_user
  %br

  = link_to 'New Tournament', new_tournament_path, :class => "btn"
- else
  %p 
    Register to create new tournaments
    = link_to "Sign Up", user_registration_path, :class => :btn

app/views/tournaments/new.html.haml
%h1 New tournament

= render 'form'

= link_to 'Back', tournaments_path

app/views/tournaments/show.html.haml
%h1
  = @tournament.name
  %small
    = @tournament.start

%p 
  %b Organised by:
  = link_to @tournament.user.username, @tournament.user

- unless @tournament.matches.empty?
  %h2 Matches

  %p
    %ul.matches
      - @tournament.matches.order('start').each do |match|
        %li
          = render :partial => 'matches/match_item', :locals => {:match => match}

- unless @tournament.participants.empty?
  
  %h2 Winners

  %p
    %ul.winners
      - @tournament.results.each do |winner|
        %li
          = winner[0]
          %span.label.label-success= winner[1]
  %h2 Participants
  %p
    %ul.participants
      - @tournament.participants.each do |user|
        %li= user

%ul.pager
  %li.previous
    = link_to 'Back', tournaments_path
  %li
    = link_to 'Edit', edit_tournament_path(@tournament)
  %li.next
    = link_to 'New Match', new_tournament_match_path(@tournament)