config/routes.rb
Rankable::Application.routes.draw do

  resources :awards, :except => [:show]
  resources :matches, :except => [:new] do
    resources :awards, :except => [:show]
  end

  resources :tournaments do
    resources :matches
  end

  resources :users, :only => [:index, :show], :path => "organisers"

  devise_for :users

  root :to => 'home#index'

end

app/models/award.rb
class Award < ActiveRecord::Base
  belongs_to :user
  belongs_to :match

  attr_accessible :amount, :user, :match_id, :username
end

app/controllers/awards_controller.rb
class AwardsController < ApplicationController
  load_and_authorize_resource :award
  
  # GET /awards
  # GET /awards.json
  def index

    match = params[:match_id]

    @awards = Award.order('created_at DESC').where(:match_id => match)
    @awards = Award.all if (@awards.empty?)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @awards }
    end
  end

  # GET /awards/new
  # GET /awards/new.json
  def new

    @award = Award.new

    if params[:match_id]
      @award.match_id = params[:match_id]
    end

    if cannot? :manage, @award.match
      raise CanCan::AccessDenied.new("You don't have permission to do that", :create, Match)
    end

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @award }
    end
  end

  # GET /awards/1/edit
  def edit
    @award = Award.find(params[:id])
  end

  # POST /awards
  # POST /awards.json
  def create

    @award = Award.new(params[:award])
    
    respond_to do |format|
      if @award.save
        format.html { redirect_to @award.match, notice: 'Award was successfully created.' }
        format.json { render json: @award, status: :created, location: @award }
      else
        format.html { render action: "new" }
        format.json { render json: @award.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /awards/1
  # PUT /awards/1.json
  def update

    @username = params[:user][:username]
    @award = Award.new(params[:award])
    
    @user = User.where(:username => @username).first

    if @user
      @award.user = @user
    else
      @award.username = @username
    end

    respond_to do |format|
      if @award.update_attributes(params[:award])
        format.html { redirect_to @award.match, notice: 'Award was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @award.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /awards/1
  # DELETE /awards/1.json
  def destroy
    @award = Award.find(params[:id])
    match = @award.match
    @award.destroy

    respond_to do |format|
      format.html { redirect_to match_awards_url(match) }
      format.json { head :no_content }
    end
  end
end

app/helpers/awards_helper.rb
module AwardsHelper
end

app/views/awards/_form.html.haml
= form_for @award, :autocomplete => false do |f|
  - if @award.errors.any?
    #error_explanation
      %h2= "#{pluralize(@award.errors.count, "error")} prohibited this award from being saved:"
      %ul
        - @award.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :user
    = f.text_field :username, :class => :typeahead, :autocomplete => false
  .field
    = f.hidden_field :match_id
  .field
    = f.label :amount
    = f.number_field :amount, :value => 0
  .actions
    = f.submit 'Save'

app/views/awards/edit.html.haml
%h1 Editing award

= render 'form'

= link_to 'Show', @award
\|
= link_to 'Back', awards_path

app/views/awards/index.html.haml
%h1 Listing awards

%table.table.table-bordered
  %tr
    %th User
    %th Match
    %th Amount
    %th Created At
    %th
    %th

  - @awards.each do |award|
    %tr
      %td= award.username
      %td= link_to award.match.name, award.match
      %td= award.amount
      %td= l award.created_at.to_time, :format => :short
      %td= link_to 'Edit', edit_award_path(award)
      %td= link_to 'Destroy', award, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Award', new_match_award_path

app/views/awards/new.html.haml
%h1 New award

= render 'form'

= link_to 'Back', match_awards_path