config/routes.rb
Rankable::Application.routes.draw do

  resources :awards, :except => [:show]
  resources :matches, :except => [:new] do
    resources :awards, :except => [:show]
  end

  resources :tournaments do
    resources :matches
  end

  resources :users, :only => [:index, :show], :path => "organisers"

  devise_for :users

  root :to => 'home#index'

end

app/models/match.rb
class Match < ActiveRecord::Base
  belongs_to :tournament
  has_many :awards

  attr_accessible :game, :name, :start, :duration, :tournament_id

  validates_presence_of :game, :tournament_id

  def p_duration
    "#{duration/60}:#{"%02d" % (duration % 60)}" 
  end

  # Total the scores by username
  def total_scores
    awards.order('amount DESC').group(:username).sum(:amount)
  end

  # Get the winner(s) for the match
  #
  # Returns an array of winners or a singleton array for a clear winner
  def winner

    if awards.count > 0
      scores = total_scores

      # Find the top scores
      top_score = scores.select { |k,v| v == scores.first[1] }

      top_score.keys
    end

  end
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  load_and_authorize_resource :match

  # GET /matches
  # GET /matches.json
  def index
    @tournament = params[:tournament_id]

    @matches = Match.where(:tournament_id => @tournament)
    @matches = Match.order('game').all unless @tournament

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @matches }
    end
  end

  # GET /matches/1
  # GET /matches/1.json
  def show
    @match = Match.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @match }
    end
  end

  # GET /matches/new
  # GET /matches/new.json
  def new
    
    @match = Match.new

    if params[:tournament_id]
      @match.tournament_id = params[:tournament_id]
    end

    if cannot? :manage, @match.tournament
      raise CanCan::AccessDenied.new("You don't have permission to do that", :create, Match)
    end

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @match }
    end
  end

  # GET /matches/1/edit
  def edit
    @match = Match.find(params[:id])
  end

  # POST /matches
  # POST /matches.json
  def create
    @match = Match.new(params[:match])

    if params[:duration]
      @match.duration = params[:duration][:hours].to_i * 60 + params[:duration][:minutes].to_i
    end

    @match.start = params[:match][:start].to_datetime + (time_to_int(params[:time])).minutes

    respond_to do |format|
      if @match.save
        format.html { redirect_to @match, notice: 'Match was successfully created.' }
        format.json { render json: @match, status: :created, location: @match }
      else
        format.html { render action: "new" }
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end
  end

  # Convert {:hour => hour, :minutes => minutes} to an integer
  def time_to_int(duration)
    duration[:hours].to_i * 60 + duration[:minutes].to_i
  end

  # PUT /matches/1
  # PUT /matches/1.json
  def update
    @match = Match.find(params[:id])

    if params[:duration]
      @match.duration = params[:duration][:hours].to_i * 60 + params[:duration][:minutes].to_i
    end

    @match.start = params[:match][:start].to_datetime + (time_to_int(params[:time])).minutes

    respond_to do |format|
      if @match.update_attributes(params[:match])
        format.html { redirect_to @match, notice: 'Match was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /matches/1
  # DELETE /matches/1.json
  def destroy
    @match = Match.find(params[:id])
    @match.destroy

    respond_to do |format|
      format.html { redirect_to matches_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/matches_helper.rb
# Helpers for dates and times
module MatchesHelper

  def time_picker(method_name, options = {})
    options[:hour] ||= 23
    options[:step] ||= 5

    %Q(
    #{select method_name, :hours, (0..options[:hour].to_i).to_a.map { |i| i }, :default => 1}
    h
    #{select method_name, :minutes, (0..59).step(options[:step].to_i)}
    m).html_safe
  end
   
end

app/views/matches/_form.html.haml
= form_for @match do |f|
  - if @match.errors.any?
    #error_explanation
      %h2= "#{pluralize(@match.errors.count, "error")} prohibited this award from being saved:"
      %ul
        - @match.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.hidden_field :tournament_id
  .field
    = f.label :game
    = f.text_field :game
  .field 
    = f.label :start
    = f.text_field :start
    = f.label :time
    = time_picker :time
  .field
    = f.label :duration
    = time_picker :duration, {:hour => 12}
  .actions
    = f.submit 'Save'

app/views/matches/_match_item.html.haml
%strong
  = link_to match.name, match
\-
%span.game
  = match.game
%span.start
  = distance_of_time_in_words match.start, Time.now
  - if match.start.past?
    ago
  - else
    away

app/views/matches/edit.html.haml
%h1 Editing match

= render 'form'

= link_to 'Show', @match
\|
= link_to 'Back', matches_path

app/views/matches/index.html.haml
%h1 
  Matches
  - if @tournament.nil?
    By Game Type

%table.table.table-bordered
  %tr
    %th Name
    %th Tournament
    %th Game
    %th
    %th
    %th

  - @matches.each do |match|
    %tr
      %td= match.name
      %td
        =link_to match.tournament.name, match.tournament
      %td= match.game
      %td= link_to 'Show', match
      %td= link_to 'Edit', edit_match_path(match)
      %td= link_to 'Destroy', match, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

-if @tournament
  = link_to 'New Match', new_tournament_match_path

app/views/matches/new.html.haml
%h1 New match

= render 'form'

= link_to 'Back', matches_path

app/views/matches/show.html.haml
%h1
  = @match.name
  %small
    = link_to @match.tournament.name, @match.tournament
%p
  %b Game:
  = @match.game

%p 
  %b Start:
  = @match.start

%p
  %b Duration:
  = @match.p_duration + "h"

- unless @match.awards.empty?

  - winner = @match.winner
  - if winner
    %h2 Outcome
    %p 
      - if winner.count == 1
        - styling = {:class => 'label-success', :message => 'has won'}
      - else
        - styling = {:class => 'label-warning', :message => 'have drawn'}

      - winners = winner.map do |user|
        - content_tag :span, user, :class => "label #{styling[:class]}"

      = winners.join(", ").html_safe
      = styling[:message]

  %p
    %h2
      Scores
    %table.table.table-bordered.awards
      %thead
        %tr
          %th Points
          %th Username
      %tbody
      - @match.total_scores.each do |award|
        %tr
          %td.text-center
            %span.badge.badge-info
              = award[1]
          %td
            = award[0]
    %p
      = link_to 'Points Breakdown', match_awards_path(@match), :class => 'btn btn-info btn-small'

%ul.pager
  %li.previous
    = link_to 'Back', tournament_matches_path(@match.tournament)
  %li
    = link_to 'Edit', edit_tournament_match_path(@match.tournament, @match)
  %li.next
    = link_to 'New Award', new_match_award_path(@match)